### ISSUE TITLE
Add remaining task list types to pages.

### ISSUE THREAD

**Issue by BobCabossa** [Mercantec-GHC/h4-projekt-gruppe-3#69]
- [ ] Create pending tasks page and get pending tasks from backend.
- [ ] Create available tasks page and get available tasks from backend.
- [ ] Create completed tasks page and get completed tasks from backend.
- [ ] #70
